spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/finaxis
    username: postgres
    password: tharun
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition: cardDetails
    stream:
      bindings:
        send-communication-out-0:
          destination: send-communication
        cardDetails-in-0:
          destination: card-details-link
          group: ${spring.application.name}
      kafka:
        binder:
          brokers: localhost:9092