spring:
  application:
    name: cards
  datasource:
    url: jdbc:postgresql://localhost:5432/finaxis
    username: postgres
    password: tharun
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        card-details-out-0:
          destination: card-details
          content-type: application/json
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

server:
  port: 8081
