spring:
  application:
    name: cards
  datasource:
    url: jdbc:postgresql://localhost:5432/finaxis
    username: postgres
    password: tharun
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        card-details-out-0:
          destination: card-details-link
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
server:
  port: 8081
