server:
  port: 8082

spring:
  application:
    name: loans
  datasource:
    url: jdbc:postgresql://localhost:5432/finaxis
    username: tharun
    password: tharun
  jpa:
    hibernate:
      ddl-auto: update


