server:
    port: 9000
spring:
  application:
    name: message
  cloud:
    function:
      definition: accountDetails; accountDetails1
    stream:
     bindings:
       accountDetails-in-0:
         destination: send-communication
         group: account
       accountDetails1-in-0:
         destination: send-communication
         group: ${spring.application.name}
     kafka:
       binder:
         brokers: localhost:9092