server:
    port: 9092
spring:
  application:
    name: message
  cloud:
    function:
      definition: accountDetails
    stream:
     bindings:
       accountDetails-in-0:
         destination: send-communication
         group: account-consumption
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s